services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DASHBOARD_BASE_URL: 'http://localhost:5173'
      CLIENT_BASE_URL: 'http://localhost:5174'
      CLIENT_REDIRECT_AFTER_LOGIN: 'http://localhost:5174/home'
    ports:
      - '4000:4080'
